settings:
    db_name: survey
    db_username: dbuser
secrets:
    db_password: ENC[AES256_GCM,data:Qo7FMKS2oi6qjDjhpRZXxg==,iv:7cxCXxYYITyini/9Nh2WZC+/CraslnJYJuH0onbTNoU=,tag:FQ45+Y9AbSARMS0TrBiddA==,type:str]
    allowed_ip: ENC[AES256_GCM,data:KyCNlIc4jU2ZFgOoyA==,iv:aYj0ZyCJg64nzmi9gL0mCVlAAewQyh6sXHY7ZYAj4us=,tag:3AkSFYNL/sJFPOLbW2f9zA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:994766090358:key/47b3f38b-44e6-4b93-a91c-55b468be614a
          created_at: "2025-05-22T14:23:46Z"
          enc: AQICAHgjuGable+/qETiXSTSpsME3I2cGhIs/6ngwSNG6Gdd7QGbWeJ+X+hkhnwaBWBIJWR6AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMf4KiOr/cCYO0XM2lAgEQgDtazUNiASgg6okdHd8JkBrpAS9ZgoKb6tqX6suHxN2PEAZv1YVq5h+CUimUkkajfDzUtDO5wbfeF4GsUQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-05-22T14:23:47Z"
    mac: ENC[AES256_GCM,data:/LM6sHmFIkZUlncdPHrZ4dqWA7IFz2WrzvWnbpsjdtJ0ZlSlgAALctTD3E1RcX3uB3Q3YUt7Qzj2Se2imdcVpJqAuPEJpnSs8JGaT5gdi53YRJBPpoOpapetBlW+yeant0DbPCeu59BSV0pfJDaxC8n7L99MKE4R+XDAlU9PQ+Y=,iv:Plw1wAx3UYKnQWHxhSnTETd4xcDYpza5Fs1ImtS0kA4=,tag:UmewazERTP7cwxePq3/auQ==,type:str]
    pgp: []
    encrypted_regex: ^(secrets)$
    version: 3.8.1
