name: Terraform

on:
  workflow_dispatch:
    inputs:
      app-path:
        description: 'Application directory'
        required: true
        type: choice
        options:
          - data_processing
          - serverless

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.app-path }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.10.3'
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -out=plan.tfplan

#  apply:
#    needs: plab
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ${{ github.event.inputs.app-path }}
#    env:
#      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
#    steps:
#      - uses: actions/checkout@v3
#      - uses: hashicorp/setup-terraform@v2
#        with: { terraform_version: '1.10.3' }
#      - run: terraform init
#      - run: terraform apply -auto-approve
